
FROM golang:1.17 AS builder
#create as builder container

ARG APP_DIR=/app

WORKDIR ${APP_DIR}

ADD main.go .
ADD go.mod .
ADD go.sum.

#copy files from host to container 
#ADD . .
# /app/main
RUN go build -o main main.go

FROM golang:1.17 

ARG APP_DIR=/app

WORKDIR ${APP_DIR}

COPY --from=builder ${APP_DIR}/main

ADD public public
ADD templates templates

#Healthcheck
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
	CMD curl -s -f http:localhost:{$APP_PORT)/healthz > /dev/null || exit 1
    
#run
ENV APP_PORT=5000
ENV INSTANCE_NAME=yuting
EXPOSE ${APP_PORT}

ENTRYPOINT ["python","main.py"]